"""Compatibility facade for the split MVTec AD 2 example modules."""

from examples.mvtec_ad2.dataloader import MVTecAD2Dataloader
from examples.mvtec_ad2.discovery import (
    ANOMALY_LABEL,
    ANOMALY_SPLIT,
    CONTROL_SPLITS,
    IMAGE_EXTENSIONS,
    NORMAL_LABEL,
    _canonical_category,
    _collect_control_samples,
    _collect_good_samples,
    _collect_public_anomaly_samples,
    _find_mask_path,
    _iter_images,
    _make_sample_id,
    _normalize_categories,
    _safe_name,
    _validate_dataset_root,
    discover_mvtecad2_categories,
)
from examples.mvtec_ad2.records import MVTecAD2Sample, MVTecAD2UseCase
from examples.mvtec_ad2.runner import (
    MVTECAD2_ROOT,
    MVTECAD2_SAVE,
    _category_save_path,
    _configuration_for_category,
    _downstream_config_for_usecase,
    _generate_and_save_hybrid_samples,
    _segmentation_for_png,
    prepare_mvtecad2_usecases,
    run_evaluation_and_visualization_for_all_usecases,
    run_evaluation_and_visualization_for_usecase,
    run_evaluation_for_all_usecases,
    run_evaluation_for_usecase,
    run_hybrid_sample_generation_for_all_usecases,
    run_hybrid_sample_generation_for_usecase,
    visualize_evaluation_for_all_usecases,
    visualize_evaluation_for_usecase,
)
from examples.mvtec_ad2.steps import (
    DEFAULT_GENERATION_STEPS,
    DEPRECATED_GENERATION_FLAGS,
    GENERATION_STEP_ALIASES,
    GENERATION_STEP_CONFLICTS,
    GENERATION_STEP_ORDER,
    PREPARE_USECASE_KEYS,
    _canonical_generation_steps,
    _default_generation_steps,
    _needs_generator_loaded,
    _normalize_generation_steps,
    _pop_prepare_kwargs,
    _reject_deprecated_generation_flags,
    _reject_unknown_kwargs,
    _validate_generation_step_conflicts,
)

__all__ = [
    "MVTECAD2_ROOT",
    "MVTECAD2_SAVE",
    "MVTecAD2Dataloader",
    "MVTecAD2Sample",
    "MVTecAD2UseCase",
    "discover_mvtecad2_categories",
    "prepare_mvtecad2_usecases",
    "run_evaluation_and_visualization_for_all_usecases",
    "run_evaluation_and_visualization_for_usecase",
    "run_evaluation_for_all_usecases",
    "run_evaluation_for_usecase",
    "run_hybrid_sample_generation_for_all_usecases",
    "run_hybrid_sample_generation_for_usecase",
    "visualize_evaluation_for_all_usecases",
    "visualize_evaluation_for_usecase",
]
